### ISSUE TITLE
Demande d'aide ou exemple formule pushbullet

### ISSUE THREAD

**Issue by romain211289** [5AMsan/assistant-kodi#2]
Bonjour,

En premier, merci pour le travail ! 
Etant un peu novice dans l'utilisation d'assistant plugins, je n'ai pas tout compris dans le module Kodi

Mon installation : assistant installé avec node sur NAS synology
- un pc avec Kodi 18 leia
- une box android avec kodi 18 leia

L'assistant fonctionne car j'utilise le module Livebox sans aucuns soucis.
De même, quand je" regarde" l'assistant sur putty, je vois bien qu'il me charge au départ les deux modules (livebox et kodi v 0.1.1).

Cependant je n'ai pas du bien comprendre la formule " kodi_METHOD#{ JSON:'Object', { nested: ['array'] } } "

Pouvez vous me donner un exemple pour mettre le menu avec Input.Home ou encore faire une recherche de série ou films.

J'ai essayé kodi_Imput.Home => dans l'assistant j'ai bien l'appel du plugin mais ensuite il me marque "undefined" ... (J'ai du loupé un truc là ^^)

Enfin, une dernière question : Est il possible de mettre 2 kodi dans l'assistant et de les différencier (ex : kodi de la chambre, kodi du salon)

Je vous remercie pour tout.

Romain W.

**Comment by 5AMsan** [comment]
Le problème venait d'un paramètre null refusé par l'API JSONRPC de Leïa.
Je viens de mettre à jour le package NPM, tu peux mettre à jour.
