### ISSUE TITLE
Probleme multi host

### ISSUE THREAD

**Issue by romain211289** [5AMsan/assistant-kodi#4]
Hello, un grand merci pour le travail ! 
Par contre j'ai essayer de mettre plusieurs hôtes, mais pourrais tu m'aider, je ne vois pas où est mon erreur... Je n'ai modifié que la partie kodi

Merci !

{
  "main": {
    "pushbullet_token": "xxx"
  },
  "plugins": {
    "kodi": {
        "hosts" : {
           "salon" : {
             "host": "192.168.1.27",
             "port": 80xx
           }
           "chambre" : {
             "host": "192.168.1.24",
             "port": 80xx
           }
         }
    },
    "livebox": {
      "ip_box": "192.168.1.11"
......

**Comment by romain211289** [comment]
et si possible pourrait me donner un exemple avec la formule pour pushbullet
j'ai essayé : kodi_VideoLibrary.GetTVShows#{ JSON: {{TextField}}, { nested: ['array'] } } 
mais je ne voit pas quoi remplacer d'autre.. 

Je cherche à pouvoir lire un épisode de série par exemple.
PS : kodi_Imput.Home : nickel !

**Comment by 5AMsan** [comment]
Pour le multihosts, c'est sur la branch mulithosts du repo GIT, je mergerai quand j'aurais pu tester plus profondément.
Il faut donc (idéalement) que Git soit installé sur ta machine qui fait tourner Assistant-Plugin. Il faudra aussi supprimer le répertoir actuel :
```
cd assistant-plugin/node_modules
rm -rf assistant-kodi
git clone --single-branch --branch multihosts https://github.com/5AMsan/assistant-kodi
```
pour ta conf : 
```
"hosts" : {
  "salon" : {
    "host": "192.168.1.27",
    "port": 80xx
  },
  "chambre" : {
    "host": "192.168.1.24",
    "port": 80xx
  }
}
```
