### ISSUE TITLE
demande de formule pushbullet

### ISSUE THREAD

**Issue by romain211289** [5AMsan/assistant-kodi#6]
Hello,

Bon, j'ai fait tout ce que je m'a donné comme explications, nickel merci! 
PS : la fonction git clone pour la branche multi host ne fonctionné pas, je l'ai fait manuellement ;)

Par contre cette fois ci je te sollicite pour que tu me donne des exemple de formule à mettre dans ifttt 

J'arrive à faire fonctionner kodi_{salon}~Imput.Home : kodi revient bien au menu

Pourrais tu me donner 3 exemples de formules pour 
- rechercher et lire une série spécifique ou un film
- mettre une chaine télé PVR spécifique
- augmenter le volume de X barres

Cela va vraiment m'aider à comprendre pour établir toutes mes formules..

Merci pour ton aide
Romain

**Comment by 5AMsan** [comment]
Hello,

J'ai ajouté la fonction "rechercher et lire".
Elle fonctionne de la façon suivante  au niveau de la conf :
`kodi_salon~sandp#scooby#tvshow` 
`kodi_HOTE~sandp#TITRE#LIBRAIRIE` 
TITRE est la recherche, LIBRAIRIE est soit `movie` soit `tvshow`
Pas d'autre argument à fournir.

Je te laisse faire les tests ;)

**Comment by 5AMsan** [comment]
Concernant le volume, la commande devrait être la suivante :
`kodi_HOTE~Application.SetVolume#{volume: 100}`
Pour le mute/unmute
`kodi_HOTE~Application.SetMute`

**Comment by 5AMsan** [comment]
Enfin pour le PVR, je dois creuser. On a pas accès aux chaînes par leur nom, il faut donc, comme pour lire un film d'après son titre, commencer par rechercher parmi les chaînes pour ensuite lancer la lecture.

**Comment by romain211289** [comment]
hello :)

Good Job!! Tout fonctionne pour les deux hosts :)

 la fonction recherche de film et série fonctionne nickel. Bon j'avoue que cela aurait été parfait si on aurait pus choisir la saison et l'épisode, où même seulement que kodi lance la série au dernier épisode regardé. mais déjà s'est super ce que tu as fait !! 

Pour les chaîne je comprend, kodi ne gère pas les noms d'origine..

Dit moi,  pense tu qu'il est possible de faire une action comme celle ci  (pour aller ma télé de la chambre) : 

kodi_chambre~Addons.ExecuteAddon#{"addonid": "script.json-cec", "command ":" activate "}

**Comment by 5AMsan** [comment]
Bien reçu. Concernant les séries, la lecture du dernier non lu est le
comportement que j'avais prévu. Testé ici avec succès. Je vais revoir le
code.
Pour le CEC, j'utilise cette commande :
```
kodi_Addons.ExecuteAddon#{"addonid":"script.json-cec","params":{"command":"standby"} }
```
Donc pour allumer :
```
kodi_Addons.ExecuteAddon#{"addonid":"script.json-cec","params":{"command":"activate"} }
```

**Comment by romain211289** [comment]
Je vais essayer ça dès demain :) je viens de réaliser que je vais même pouvoir gérer un arrêt automatique de la télé une heure après ^^  le google home devient vraiment intéressant ! Du coup j essaye de bosser le js pour créer d autre possibilité de modules :D. En tout cas là s est un régale de pouvoir gérer la télé de la chambre à le voix. J espère que tu trouvera une solurion pour les chaines PVR :)

Merci pour tout!

**Comment by 5AMsan** [comment]
Je confirme, sur chacun de mes hôtes, la fonction rechercher et lire lit bien le dernier épisode non lu de la série demandée.

**Comment by romain211289** [comment]
hello; bon je viens de mettre à jour l'assistant (en dézippant le nouveau dossier), mais ça revient toujours à l'épisode 1 saison 1 sur mes hosts.. Peut être un mauvais paramétrage du logiciel kodi. Je vais chercher.

**Comment by 5AMsan** [comment]
Assure-toi que l'état déjà vu a été basculé au moins sur le premier épisode

Le dim. 24 févr. 2019 à 11:59, romain211289 <notifications@github.com> a
écrit :
